language: go
env:
  GO111MODULE=on
deploy:
  provider: heroku
  api_key:
    secure: "w2Nty0LPySALqaHTfrBzZ523Fr6KQlBktZuiL0R++0bZb02GxJaV4ONcriI10FNHUecguwdslOqrroh7XYsSEgj8gbZ/aZs168trx4jgipXNKK3QUzdCQErpOGVKmJD2cMZS2Ji/iQvW//k/osvDOZNysW8ly9H6+YsvYDjE1XKnFrrkbKmgamuTv9iPbtO+D+P0i1zME8G33oRnC2/cxjR0p841tQ1E5m6nQawvqRhgyGB1LIEy4RxP13Tvu98w0NeuTcet5uRNx5eGJPYu0YZLXO8yMknE2L6gvZ1/FtEcTtYkRoP7KTRTcgHV8eFG0QW2oLhvqeB4ehYQv6cca1Rqe7CSdc3FyN5WPKO55HSZGtFGVZ6vLOWQqB+T2D6++WrpiLKC7s59NBS9fI8JAKGoL53kV4JEyksbM7IfZyULjf9LJn5D/vm6pNbfK7w5MwPN7js3fTqe18K6my6h62JZSbuem7hzfAPKjSplZpwKrXMnpJC90ledr/rIuECQ3srpqYQqrM7j/Ia6s2AxiJdaZZg+EYHsTtJwBQp0CNWNz0NqAtqiBZqrSs3ArdfFLWdbfiV8AK79bCovIqpXzSkKKX12YeH46pnvuj+gCeDckfduDAnWUh1kCOWeoD4Llg5RRjuOa2bnr+bS9trKQVDuBHyM2OPQe8TmvKwphvw="
  app:
    ci-cd: pokemon-api-alequesada2012